Fixed a potenmtial bug causing a compiler error
./test/skiplist_test.c: In function ‘main’:                                                                                                                                                       [426/1905]
./test/skiplist_test.c:24:27: error: ‘%d’ directive output may be truncated writing between 1 and 11 bytes into a region of size 4 [-Werror=format-truncation=]
   24 |         snprintf(val, 4, "%d", i);
      |                           ^~
./test/skiplist_test.c:24:26: note: directive argument in the range [-2147483647, 99]
   24 |         snprintf(val, 4, "%d", i);
      |                          ^~~~
./test/skiplist_test.c:24:9: note: ‘snprintf’ output between 2 and 12 bytes into a destination of size 4
   24 |         snprintf(val, 4, "%d", i);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors